local K = {}
local COOKIE_KEYS = K

K.AUTO_BUY_IN = "AUTO_BUY_IN"
K.AUTO_SIT = "AUTO_SIT"
K.SHOCK = "SHOCK"
K.VOLUME = "VOLUME"

K.LAST_LOGIN_TYPE = "LAST_LOGIN_TYPE"
K.LOGINED_DEVICE = "LOGINED_DEVICE"
K.USER_FIRST_DEALER_SEND_CHIP = "USER_FIRST_DEALER_SEND_CHIP" -- 用户第一次给荷官送筹码(预留)
K.RECORD_SEND_DEALER_CHIP_TIME = "RECORD_SEND_DEALER_CHIP_TIME" -- 记录给荷官送筹码的次数

return COOKIE_KEYS
